In [13]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("DigitalAd_dataset.csv")

In [4]:
df.head()

   Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
3   45   26000       1
4   46   28000       1

In [5]:
df.tail()

     Age  Salary  Status
395   35   65000       0
396   26   80000       0
397   26   52000       0
398   20   86000       0
399   32   18000       0

In [6]:
df.shape

(400, 3)

In [9]:
#segregate dataset into x and y

x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [10]:
#spliting dataset into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [11]:
#feature scale
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)

[[ 0.97446763  0.56400811]
 [-1.52088611 -1.28151705]
 [ 0.30264162  0.03671521]
 [-0.36918439 -0.81281224]
 [ 0.49459191  1.20847722]
 [-0.1772341   0.82765456]
 [-0.27320924 -0.78351819]
 [ 0.39861676  0.24177356]
 [-0.27320924  0.00742116]
 [ 0.01471619 -0.60775389]
 [ 0.11069133  0.00742116]
 [-0.46515953  2.29235707]
 [ 0.39861676 -0.02187289]
 [-0.27320924 -1.28151705]
 [ 1.93421906 -1.39869325]
 [-0.27320924  2.23376897]
 [ 0.11069133  1.03271291]
 [-0.56113467  1.44282962]
 [ 0.97446763  1.85294632]
 [ 0.30264162  0.03671521]
 [-1.13698554 -1.04716465]
 [-0.08125895  0.27106761]
 [ 0.30264162 -0.54916579]
 [-0.27320924 -0.60775389]
 [ 0.87849248 -1.39869325]
 [ 0.78251734 -0.34410744]
 [-0.46515953 -1.252223  ]
 [ 0.20666648  0.12459736]
 [ 0.39861676  0.97412481]
 [-0.56113467  1.35494747]
 [-0.46515953 -0.05116694]
 [-0.56113467  2.32165112]
 [-0.75308496  0.27106761]
 [ 1.16641791 -0.78351819]
 [ 0.20666648  1.06200696]
 [ 0.20666648 -0.40269554]
 [ 0.30264162 -0.31481339]
 [ 0.20666648  2.08729872]
 [ 1.45434334  0.97412481]
 [-1.04101039  1.94082847]
 [-1.32893582 -1.39869325]
 [-0.27320924 -0.92998845]
 [-0.94503525  0.38824381]
 [-0.75308496 -1.57445755]
 [ 1.07044277  0.50542001]
 [-0.1772341  -0.54916579]
 [ 0.11069133  0.06600926]
 [ 0.68654219  1.76506417]
 [-0.27320924  0.76906646]
 [-0.65710982 -0.37340149]
 [ 0.87849248  1.00341886]
 [-0.94503525 -0.46128364]
 [-0.08125895  0.24177356]
 [ 0.39861676 -0.16834314]
 [ 0.39861676  0.27106761]
 [-1.13698554 -1.63304565]
 [-0.08125895  0.21247951]
 [-1.80881154  0.41753786]
 [ 2.03019421 -0.84210629]
 [ 1.07044277  2.05800467]
 [-0.1772341  -0.22693124]
 [ 0.30264162 -1.1936349 ]
 [-1.04101039 -0.49057769]
 [ 0.68654219 -0.75422414]
 [-0.27320924 -0.69563604]
 [-0.75308496  1.88224037]
 [ 1.26239306  2.20447492]
 [-0.08125895  0.00742116]
 [-0.94503525 -0.98857655]
 [-0.36918439  1.20847722]
 [-0.65710982  0.00742116]
 [ 0.39861676  0.06600926]
 [ 0.87849248 -0.81281224]
 [-1.04101039 -0.37340149]
 [ 0.30264162  0.03671521]
 [ 0.97446763  0.09530331]
 [ 0.20666648  0.12459736]
 [-1.04101039 -1.4865754 ]
 [ 1.83824392 -0.31481339]
 [-1.13698554  0.27106761]
 [ 0.78251734  0.32965571]
 [-0.94503525  0.41753786]
 [ 0.30264162 -0.75422414]
 [ 0.78251734 -0.87140035]
 [ 0.01471619  1.20847722]
 [-0.27320924 -0.31481339]
 [-0.75308496 -1.63304565]
 [-0.36918439 -0.81281224]
 [-0.08125895  0.27106761]
 [-0.08125895  0.65189026]
 [-1.32893582 -0.37340149]
 [ 0.01471619 -0.16834314]
 [ 1.93421906 -0.69563604]
 [-0.46515953 -0.57845984]
 [ 0.87849248 -1.34010515]
 [ 0.11069133 -0.84210629]
 [-1.61686125  0.50542001]
 [-0.1772341   1.61859392]
 [ 0.97446763 -1.10575275]
 [ 0.78251734  0.24177356]
 [-0.65710982  0.15389141]
 [ 0.59056705 -0.92998845]
 [ 1.07044277  0.44683191]
 [ 0.30264162  0.24177356]
 [ 1.64629363 -0.92998845]
 [ 1.45434334  0.32965571]
 [-0.08125895  2.20447492]
 [-0.65710982  0.53471406]
 [ 0.78251734  0.73977241]
 [-1.04101039  0.38824381]
 [ 0.11069133 -0.84210629]
 [-1.13698554  0.03671521]
 [ 1.45434334  0.03671521]
 [-1.52088611 -1.5451635 ]
 [ 1.3583682   0.56400811]
 [-0.75308496  0.53471406]
 [-1.04101039  0.53471406]
 [ 0.11069133 -0.28551934]
 [-1.13698554 -1.6037516 ]
 [-1.04101039 -0.40269554]
 [ 1.16641791 -1.4865754 ]
 [ 1.55031849 -0.02187289]
 [-1.04101039 -0.37340149]
 [-1.61686125 -1.6037516 ]
 [ 0.68654219  0.24177356]
 [-0.8490601  -1.252223  ]
 [-0.27320924  0.03671521]
 [-1.23296068 -1.10575275]
 [-0.65710982  1.38424152]
 [ 0.87849248 -1.1936349 ]
 [ 0.97446763 -1.10575275]
 [ 1.74226877  1.82365227]
 [ 1.07044277 -1.0178706 ]
 [-1.13698554 -0.81281224]
 [ 1.16641791  0.50542001]
 [-0.36918439  0.03671521]
 [ 0.20666648 -0.34410744]
 [-1.42491097 -1.252223  ]
 [-0.94503525  1.53071177]
 [ 0.30264162  0.00742116]
 [-1.13698554 -0.54916579]
 [-0.75308496  0.47612596]
 [ 0.87849248  2.14588682]
 [ 0.11069133  1.85294632]
 [-0.08125895  2.14588682]
 [ 0.97446763 -1.04716465]
 [ 0.30264162 -0.57845984]
 [-0.27320924 -0.9592825 ]
 [-0.36918439  1.29635937]
 [-1.52088611 -0.46128364]
 [-0.65710982  0.09530331]
 [ 1.3583682  -1.45728135]
 [-0.27320924 -0.60775389]
 [-0.27320924 -0.51987174]
 [-0.27320924  0.12459736]
 [ 2.03019421  2.11659277]
 [ 0.87849248  1.06200696]
 [-0.1772341  -0.60775389]
 [-0.08125895 -0.54916579]
 [ 0.20666648 -0.16834314]
 [ 1.64629363  1.58929987]
 [ 0.30264162 -0.54916579]
 [-0.94503525 -0.78351819]
 [ 0.39861676  2.29235707]
 [ 1.3583682   1.97012252]
 [ 0.68654219 -1.3108111 ]
 [ 0.11069133  1.85294632]
 [-1.80881154 -1.34010515]
 [-0.75308496  1.32565342]
 [-1.13698554  0.27106761]
 [ 0.11069133  0.12459736]
 [ 2.12616935 -0.84210629]
 [ 0.49459191  1.70647607]
 [-0.75308496  0.24177356]
 [ 2.12616935 -0.72493009]
 [-0.8490601   0.35894976]
 [ 2.12616935 -0.84210629]
 [ 0.87849248 -1.4865754 ]
 [ 0.01471619 -0.60775389]
 [-1.04101039  0.50542001]
 [ 2.03019421  0.50542001]
 [-1.32893582 -1.1350468 ]
 [ 1.26239306 -1.39869325]
 [-1.7128364  -1.39869325]
 [-1.32893582 -0.46128364]
 [ 0.97446763  2.05800467]
 [ 2.03019421  0.35894976]
 [ 2.12616935  0.91553671]
 [ 0.97446763  1.41353557]
 [ 0.01471619 -0.57845984]
 [ 0.30264162 -0.22693124]
 [-0.75308496  1.06200696]
 [ 0.20666648 -0.40269554]
 [-1.90478668 -0.54916579]
 [ 1.55031849  0.97412481]
 [-0.36918439 -1.34010515]
 [ 1.07044277  0.09530331]
 [-0.75308496 -0.63704794]
 [-0.94503525  0.24177356]
 [-1.90478668  0.32965571]
 [ 2.12616935  1.09130101]
 [-0.08125895 -0.40269554]
 [ 0.01471619 -0.28551934]
 [-0.27320924 -1.4865754 ]
 [-0.8490601  -0.81281224]
 [ 0.49459191  1.82365227]
 [-1.13698554  0.44683191]
 [ 1.07044277 -1.252223  ]
 [ 0.01471619  0.27106761]
 [ 2.03019421 -1.22292895]
 [-0.46515953 -0.81281224]
 [-0.27320924  0.50542001]
 [-0.1772341  -0.31481339]
 [-1.42491097 -0.13904909]
 [-0.27320924  0.59330216]
 [-0.08125895  0.18318546]
 [ 0.01471619 -0.34410744]
 [-0.08125895 -1.10575275]
 [-0.8490601   0.12459736]
 [-0.94503525  0.53471406]
 [-1.32893582  0.53471406]
 [ 2.12616935  0.35894976]
 [-1.7128364   0.44683191]
 [ 0.01471619  0.00742116]
 [ 0.01471619 -0.46128364]
 [ 0.20666648  0.21247951]
 [-0.27320924  0.06600926]
 [-1.42491097 -0.22693124]
 [ 0.39861676 -0.49057769]
 [ 0.39861676 -0.19763719]
 [-1.61686125  0.03671521]
 [-0.27320924 -1.34010515]
 [-0.27320924 -0.28551934]
 [-1.61686125 -0.08046099]
 [ 0.39861676 -0.49057769]
 [-1.32893582 -1.28151705]
 [-0.1772341  -0.49057769]
 [ 2.03019421  0.15389141]
 [ 1.55031849 -1.3108111 ]
 [-1.42491097 -0.66634199]
 [ 0.30264162 -0.34410744]
 [ 0.59056705  1.99941657]
 [ 0.97446763  1.97012252]
 [ 0.78251734  0.50542001]
 [-0.8490601   0.35894976]
 [-1.42491097  0.32965571]
 [ 1.45434334 -1.0764587 ]
 [-0.27320924 -0.34410744]
 [ 0.20666648 -0.31481339]
 [-0.27320924  1.09130101]
 [-1.7128364  -1.0178706 ]
 [-1.23296068 -1.4279873 ]
 [-1.90478668  0.44683191]
 [ 1.93421906  0.71047836]
 [ 1.07044277 -0.16834314]
 [-1.42491097 -1.4865754 ]
 [-1.23296068  0.24177356]
 [-1.90478668 -0.08046099]
 [-0.27320924 -1.4279873 ]
 [ 1.07044277 -0.92998845]
 [-0.08125895  1.94082847]
 [ 0.78251734  0.09530331]
 [-1.23296068  0.56400811]
 [ 0.78251734  1.35494747]
 [ 1.83824392 -1.10575275]
 [-1.80881154 -1.3108111 ]
 [-0.08125895 -0.46128364]
 [ 0.39861676  0.56400811]
 [ 0.01471619 -0.28551934]
 [ 1.3583682   2.32165112]
 [ 0.20666648 -0.40269554]
 [-1.13698554  0.38824381]
 [ 1.16641791 -1.0178706 ]
 [-1.32893582 -0.46128364]
 [ 1.55031849  1.09130101]
 [-1.04101039 -1.16434085]
 [-0.65710982 -1.0764587 ]
 [-0.08125895  0.12459736]
 [-0.1772341  -1.10575275]
 [-0.27320924  0.03671521]
 [-1.80881154 -1.51586945]
 [-0.27320924 -1.39869325]
 [ 1.3583682   1.26706532]
 [-0.1772341   1.38424152]
 [-0.56113467  0.44683191]
 [-0.75308496 -0.25622529]
 [-0.94503525 -0.34410744]
 [ 1.26239306  1.85294632]
 [ 0.30264162  0.03671521]
 [ 1.07044277  0.53471406]
 [-0.08125895 -0.51987174]
 [ 0.68654219 -1.4279873 ]
 [ 2.03019421  1.73577012]
 [ 0.78251734 -1.4279873 ]
 [ 0.39861676  1.09130101]
 [-0.27320924  0.24177356]
 [ 1.64629363  1.73577012]
 [-0.46515953 -1.16434085]
 [-1.23296068  0.47612596]
 [-1.7128364   0.32965571]]

In [12]:
#train the data

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [15]:
#prediction for all test data for evaluate
y_pred=model.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]

In [22]:
#validation

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print("confusion matrix: ")
print(cm)
print("Accuracy of the model:{0}%".format(accuracy_score(y_test,y_pred)*100))

confusion matrix:
[[61  0]
 [20 19]]
Accuracy of the model:80.0%

In [25]:
#testing data

age=int(input("enter new customer's age:"))
sal=int(input("enter newcustomer's salary "))
newcust=[[age,sal]]
result=model.predict(sc.transform(newcust))
print(result)
if result==1:
    print("customer will buy")
else:
    print("customer won't buy")

enter new customer's age:32
enter newcustomer's salary 7800
[0]
customer won't buy